P1;<A class="explorer" HREF="JavaScript:void(null)"onclick="toggleMenu('parent',1)"><FONT CLASS=menu>Maintain Codes</FONT></A>
P2;<A class="explorer" HREF="JavaScript:void(null)"onclick="toggleMenu('parent',2)"><FONT CLASS=menu>Enter Applications</FONT></A>
P3;<A class="explorer" HREF="JavaScript:void(null)"onclick="toggleMenu('parent',3)"><FONT CLASS=menu>Licences & Conditions</FONT></A>
P4;<A class="explorer" HREF="JavaScript:void(null)"onclick="toggleMenu('parent',4)"><FONT CLASS=menu>Enquiries & Reports</FONT></A>
P5;<A class="explorer" HREF="JavaScript:void(null)"onclick="toggleMenu('parent',5)"><FONT CLASS=menu>Security</FONT></A>
O1;<A class="logoff"   HREF="/prospect/asp/abandon.asp"onmouseover="linkUp('parent',9);window.status='';"onmouseout="linkDn('parent',9)"><FONT CLASS=menu>Log Off</FONT></A>
C1;<A class="explorer" HREF="/prospect/asp/binput.asp?fn=@@PATH@@\ckashare\build\build.mdb\structure&tn=ibuild_structure_codes&item=empty&baditem=empty&blank=yes&err=noerrors&found=yes" "@@MOUSE@@"><FONT CLASS=menu>Structure Codes</FONT></A>
C1;<A class="explorer" HREF="/prospect/asp/binput.asp?fn=@@PATH@@\ckashare\build\build.mdb\work&tn=ibuild_work_codes&item=empty&baditem=empty&blank=yes&err=noerrors&found=yes" "@@MOUSE@@"><FONT CLASS=menu>Work Codes</FONT></A>
C1;<A class="explorer" HREF="/prospect/asp/binput.asp?fn=@@PATH@@\ckashare\build\build.mdb\building&tn=ibuild_building_codes&item=empty&baditem=empty&blank=yes&err=noerrors&found=yes" "@@MOUSE@@"><FONT CLASS=menu>Building Codes</FONT></A>
C1;<A class="explorer" HREF="/prospect/asp/binput.asp?fn=@@PATH@@\ckashare\build\build.mdb\other&tn=ibuild_other_codes&item=empty&baditem=empty&blank=yes&err=noerrors&found=yes" "@@MOUSE@@"><FONT CLASS=menu>Other Building Codes</FONT></A>
C1;<A class="explorer" HREF="/prospect/asp/binput.asp?fn=@@PATH@@\ckashare\build\build.mdb\wall&tn=ibuild_wall_codes&item=empty&baditem=empty&blank=yes&err=noerrors&found=yes" "@@MOUSE@@"><FONT CLASS=menu>Wall Material Codes</FONT></A>
C1;<A class="explorer" HREF="/prospect/asp/binput.asp?fn=@@PATH@@\ckashare\build\build.mdb\roof&tn=ibuild_roof_codes&item=empty&baditem=empty&blank=yes&err=noerrors&found=yes" "@@MOUSE@@"><FONT CLASS=menu>Roof Material Codes</FONT></A>
C1;<A class="explorer" HREF="/prospect/asp/binput.asp?fn=@@PATH@@\ckashare\build\build.mdb\floor&tn=ibuild_floor_codes&item=empty&baditem=empty&blank=yes&err=noerrors&found=yes" "@@MOUSE@@"><FONT CLASS=menu>Floor Material Codes</FONT></A>
C1;<A class="explorer" HREF="/prospect/asp/binput.asp?fn=@@PATH@@\ckashare\build\build.mdb\frame&tn=ibuild_frame_codes&item=empty&baditem=empty&blank=yes&err=noerrors&found=yes" "@@MOUSE@@"><FONT CLASS=menu>Frame Type Codes</FONT></A>
C1;<A class="explorer" HREF="/prospect/asp/binput.asp?fn=@@PATH@@\ckashare\build\build.mdb\dept&tn=ibuild_department_codes&item=empty&baditem=empty&blank=yes&err=noerrors&found=yes" "@@MOUSE@@"><FONT CLASS=menu>Department Codes</FONT></A>
C1;<A class="explorer" HREF="/prospect/asp/binput.asp?fn=@@PATH@@\ckashare\build\build.mdb\inspection&tn=ibuild_inspection_codes&item=empty&baditem=empty&blank=yes&err=noerrors&found=yes" "@@MOUSE@@"><FONT CLASS=menu>Inspection Codes</FONT></A>
C1;<A class="explorer" HREF="/prospect/asp/binput.asp?fn=@@PATH@@\ckashare\build\build.mdb\soil&tn=ibuild_soil_codes&item=empty&baditem=empty&blank=yes&err=noerrors&found=yes" "@@MOUSE@@"><FONT CLASS=menu>Soil Type Codes</FONT></A>
C1;<A class="explorer" HREF="/prospect/asp/binput.asp?fn=@@PATH@@\ckashare\build\build.mdb\surveyor&tn=ibuild_surveyor_codes&item=empty&baditem=empty&blank=yes&err=noerrors&found=yes" "@@MOUSE@@"><FONT CLASS=menu>Surveyor Codes</FONT></A>
C1;<A class="explorer" HREF="/prospect/asp/binput.asp?fn=@@PATH@@\ckashare\build\build.mdb\suburb&tn=ibuild_suburb_codes&item=empty&baditem=empty&blank=yes&err=noerrors&found=yes" "@@MOUSE@@"><FONT CLASS=menu>Suburb Codes</FONT></A>
C1;<A class="explorer" HREF="/prospect/asp/binput.asp?fn=@@PATH@@\ckashare\build\build.mdb\insurer&tn=ibuild_insurer_codes&item=empty&baditem=empty&blank=yes&err=noerrors&found=yes" "@@MOUSE@@"><FONT CLASS=menu>Insurer Codes</FONT></A>
C1;<A class="explorer" HREF="/prospect/asp/binput.asp?fn=@@PATH@@\ckashare\build\build.mdb\pending&tn=ibuild_pending_codes&item=empty&baditem=empty&blank=yes&err=noerrors&found=yes" "@@MOUSE@@"><FONT CLASS=menu>Pending Reason Codes</FONT></A>
C1;<A class="explorer" HREF="/prospect/asp/binput.asp?fn=@@PATH@@\ckashare\build\build.mdb\bca&tn=ibuild_bca_codes&item=empty&baditem=empty&blank=yes&err=noerrors&found=yes" "@@MOUSE@@"><FONT CLASS=menu>BCA Codes</FONT></A>
C1;<A class="explorer" HREF="/prospect/asp/binput.asp?fn=@@PATH@@\ckashare\build\build.mdb\condition&tn=ibuild_condition_codes&item=empty&baditem=empty&blank=yes&err=noerrors&found=yes" "@@MOUSE@@"><FONT CLASS=menu>Condition Codes</FONT></A>
C1;<A class="explorer" HREF="/prospect/asp/binput.asp?fn=@@PATH@@\ckashare\build\build.mdb\fee&tn=ibuild_fee_codes&item=empty&baditem=empty&blank=yes&err=noerrors&found=yes" "@@MOUSE@@"><FONT CLASS=menu>Fee Codes</FONT></A>
C2;<A class="explorer" HREF="/prospect/asp/binput.asp?fn=plans&tn=iplans&item=empty&baditem=empty&blank=yes&err=noerrors&found=yes" target="plans_input" onmouseover="linkUp('child4',2)"onmouseout="linkDn('child4',2)"><FONT CLASS=menu>Maintain Building Applications</FONT></A>
C3;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Building Applications""@@MOUSE@@"><FONT CLASS=menu>Building Applications</FONT></A>
C4;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Building Applications""@@MOUSE@@"><FONT CLASS=menu>Enquiries & Reports</FONT></A>
C4;<A class="explorer" HREF="/prospect/reports/plans/3148 Building Licence Applications by Month.asp?sentence=&reportname=3148 Building Licence Applications by Month&template=plans""@@MOUSE@@"><FONT CLASS=menu>Building Licence Applications by Month</FONT></A>
C4;<A class="explorer" HREF="/prospect/reports/plans/3131 Building Statistics.asp?sentence=&reportname=3131 Building Statistics&template=plans""@@MOUSE@@"><FONT CLASS=menu>Building Statistics</FONT></A>
C5;<A class="explorer" HREF="/prospect/asp/group_admin.asp""@@MOUSE@@"><FONT CLASS=menu>Maintain Groups</FONT></A>
C5;<A class="explorer" HREF="/prospect/asp/user_admin.asp""@@MOUSE@@"><FONT CLASS=menu>Maintain Users</FONT></A>