P1;<A class="explorer" HREF="JavaScript:void(null)"onclick="toggleMenu('parent',1)"><FONT CLASS=menu>Administration</FONT></A>
P2;<A class="explorer" HREF="JavaScript:void(null)"onclick="toggleMenu('parent',2)"><FONT CLASS=menu>Community</FONT></A>
P3;<A class="explorer" HREF="JavaScript:void(null)"onclick="toggleMenu('parent',3)"><FONT CLASS=menu>Engineering</FONT></A>
P4;<A class="explorer" HREF="JavaScript:void(null)"onclick="toggleMenu('parent',4)"><FONT CLASS=menu>Financial</FONT></A>
P5;<A class="explorer" HREF="JavaScript:void(null)"onclick="toggleMenu('parent',5)"><FONT CLASS=menu>Library</FONT></A>
P6;<A class="explorer" HREF="JavaScript:void(null)"onclick="toggleMenu('parent',6)"><FONT CLASS=menu>Property</FONT></A>
P7;<A class="explorer" HREF="JavaScript:void(null)"onclick="toggleMenu('parent',7)"><FONT CLASS=menu>Rates</FONT></A>
P8;<A class="explorer" HREF="JavaScript:void(null)"onclick="toggleMenu('parent',8)"><FONT CLASS=menu>Security</FONT></A>
O1;<A class="explorer" HREF="JavaScript:void(null)"onclick="logis_menu()"onmouseover="linkUp('parent',9);window.status='';"onmouseout="linkDn('parent',9)"><FONT CLASS=menu>Logis Menus</FONT></A>
O2;<A class="explorer" HREF="/prospect/logis/sld001.htm"onmouseover="linkUp('parent',10);window.status='';"onmouseout="linkDn('parent',10)"><FONT CLASS=menu>About Logis</FONT></A>
O3;<A class="explorer" HREF="/prospect/news/articles.html" onmouseover="linkUp('parent',11);window.status='';" onmouseout="linkDn('parent',11)"><FONT CLASS=menu>Newsletters</FONT></A>
O4;<A class="explorer" HREF="/prospect/asp/search.asp?sn=PROSPECT Manual"onmouseover="linkUp('parent',12);window.status='';"onmouseout="linkDn('parent',12)"><font class=menu>PROSPECT Manual</font></A>
O5;<A class="logoff"   HREF="/prospect/asp/abandon.asp"onmouseover="linkUp('parent',13);window.status='';"onmouseout="linkDn('parent',13)"><FONT CLASS=menu>Log Off</FONT></A>
C1_1;<A class="explorer" HREF="/prospect/asp/logis_menus.asp?sn=Filing"target="new"onmouseover="linkUp('child1',1)"onmouseout="linkDn('child1',1)"><FONT CLASS=menu>Filing</FONT></A>
C2_1;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Clubs"onmouseover="linkUp('child2',1)"onmouseout="linkDn('child2',1)"><FONT CLASS=menu>Clubs</FONT></A>
C2_2;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Government Depts"onmouseover="linkUp('child2',2)"onmouseout="linkDn('child2',2)"><FONT CLASS=menu>Government Depts.</FONT></A>
C2_3;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Council Information"onmouseover="linkUp('child2',3)"onmouseout="linkDn('child2',3)"><FONT CLASS=menu>Information</FONT></A>
C2_4;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Council Listings"onmouseover="linkUp('child2',4)"onmouseout="linkDn('child2',4)"><FONT CLASS=menu>Listings</FONT></A>
C2_5;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Events"onmouseover="linkUp('child2',5)"onmouseout="linkDn('child2',5)"><FONT CLASS=menu>Events</FONT></A>
C2_6;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Halls and Recreation"onmouseover="linkUp('child2',6)"onmouseout="linkDn('child2',6)"><FONT CLASS=menu>Halls & Recreation</FONT></A>
C2_7;<A class="explorer" HREF="/prospect/asp/search.asp?sn=General Infringements"onmouseover="linkUp('child2',7)"onmouseout="linkDn('child2',7)"><FONT CLASS=menu>Infringements</FONT></A>
C2_8;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Animal Pickups"onmouseover="linkUp('child2',8)"onmouseout="linkDn('child2',8)"><FONT CLASS=menu>Pickups</FONT></A>
C2_9;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Parking Infringements"onmouseover="linkUp('child2',9)"onmouseout="linkDn('child2',9)"><FONT CLASS=menu>Parking</FONT></A>
C2_10;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Customer Service Log"onmouseover="linkUp('child2',10)"onmouseout="linkDn('child2',10)"><FONT CLASS=menu>CS Log</FONT></A>
C3_1;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Job Estimating"onmouseover="linkUp('child3',1)"onmouseout="linkDn('child3',1)"><FONT CLASS=menu>Job Estimating</FONT></A>
C3_2;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Job Costing"onmouseover="linkUp('child3',2)"onmouseout="linkDn('child3',2)"><FONT CLASS=menu>Job Costing</FONT></A>
C3_3;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Plant Maintenance"onmouseover="linkUp('child3',3)"onmouseout="linkDn('child3',3)"><FONT CLASS=menu>Plant Maintenance</FONT></A>
C4_1;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Display Assets"onmouseover="linkUp('child4',1)"onmouseout="linkDn('child4',1)"><FONT CLASS=menu>Display Assets</FONT></A>
C4_2;<A class="explorer" HREF="/prospect/asp/binput.asp?fn=asset&tn=iasset&item=empty&baditem=empty&blank=yes&err=noerrors&found=yes" target="asset_input" onmouseover="linkUp('child4',2)"onmouseout="linkDn('child4',2)"><FONT CLASS=menu>Maintain Assets</FONT></A>
C4_3;<A HREF="/prospect/asp/bmenu.asp?tn=menu_asset_register" onmouseover="linkUp('child4',3)"onmouseout="linkDn('child4',3)"><FONT CLASS=menu>Asset Register Menu</FONT></A>
C4_4;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Creditors"onmouseover="linkUp('child4',4)"onmouseout="linkDn('child4',4)"><FONT CLASS=menu>Creditors</FONT></A>
C4_5;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Creditor Invoices"onmouseover="linkUp('child4',5)"onmouseout="linkDn('child4',5)"><FONT CLASS=menu>Creditor Invoices</FONT></A>
C4_6;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Cheques"onmouseover="linkUp('child4',6)"onmouseout="linkDn('child4',6)"><FONT CLASS=menu>Cheques</FONT></A>
C4_7;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Cheque Remittances"onmouseover="linkUp('child4',7)"onmouseout="linkDn('child4',7)"><FONT CLASS=menu>Cheque Remittances</FONT></A>
C4_8;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Debtors"onmouseover="linkUp('child4',8)"onmouseout="linkDn('child4',8)"><FONT CLASS=menu>Debtors</FONT></A>
C4_9;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Debtor Invoices"onmouseover="linkUp('child4',9)"onmouseout="linkDn('child4',9)"><FONT CLASS=menu>Debtor Invoices</FONT></A>
C4_10;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Cash Receipts"onmouseover="linkUp('child4',10)"onmouseout="linkDn('child4',10)"><FONT CLASS=menu>Cash Receipts</FONT></A>
C4_11;<A class="explorer" HREF="/prospect/asp/search.asp?sn=General Ledger"onmouseover="linkUp('child4',11)"onmouseout="linkDn('child4',11)"><FONT CLASS=menu>General Ledger</FONT></A>
C4_12;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Investments"onmouseover="linkUp('child4',12)"onmouseout="linkDn('child4',12)"><FONT CLASS=menu>Investments</FONT></A>
C4_13;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Journals"onmouseover="linkUp('child4',13)"onmouseout="linkDn('child4',13)"><FONT CLASS=menu>Journals</FONT></A>
C4_14;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Loans"onmouseover="linkUp('child4',14)"onmouseout="linkDn('child4',14)"><FONT CLASS=menu>Loans</FONT></A>
C4_15;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Purchase Orders"onmouseover="linkUp('child4',15)"onmouseout="linkDn('child4',15)"><FONT CLASS=menu>Purchase Orders</FONT></A>
C4_16;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Stock Catalogue"onmouseover="linkUp('child4',16)"onmouseout="linkDn('child4',16)"><FONT CLASS=menu>Stock Catalogue</FONT></A>
C5_1;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Opac"onmouseover="linkUp('child5',1)"onmouseout="linkDn('child5',1)"><FONT CLASS=menu>Opac</FONT></A>
C6_1;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Property"onmouseover="linkUp('child6',1)"onmouseout="linkDn('child6',1)"><FONT CLASS=menu>Property</FONT></A>
C6_2;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Clients"onmouseover="linkUp('child6',2)"onmouseout="linkDn('child6',2)"><FONT CLASS=menu>Clients</FONT></A>
C6_3;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Animals"onmouseover="linkUp('child6',3)"onmouseout="linkDn('child6',3)"><FONT CLASS=menu>Animals</FONT></A>
C6_4;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Building Applications"onmouseover="linkUp('child6',4)"onmouseout="linkDn('child6',4)"><FONT CLASS=menu>Building Applications</FONT></A>
C6_5;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Crossovers"onmouseover="linkUp('child6',5)"onmouseout="linkDn('child6',5)"><FONT CLASS=menu>Crossovers</FONT></A>
C6_6;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Demolitions"onmouseover="linkUp('child6',6)"onmouseout="linkDn('child6',6)"><FONT CLASS=menu>Demolitions</FONT></A>
C6_7;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Health Premises"onmouseover="linkUp('child6',7)"onmouseout="linkDn('child6',7)"><FONT CLASS=menu>Health</FONT></A>
C6_8;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Signs"onmouseover="linkUp('child6',8)"onmouseout="linkDn('child6',8)"><FONT CLASS=menu>Signs</FONT></A>
C6_9;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Pools"onmouseover="linkUp('child6',9)"onmouseout="linkDn('child6',9)"><FONT CLASS=menu>Swimming Pools</FONT></A>
C6_10;<A class="explorer" HREF="/prospect/asp/search.asp?sn=Rubbish Bins"onmouseover="linkUp('child6',10)"onmouseout="linkDn('child6',10)"><FONT CLASS=menu>Rubbish Bins</FONT></A>
C6_11;<A class="explorer" HREF="/prospect/asp/bi.asp?tn=extended_database"onmouseover="linkUp('child6',11)"onmouseout="linkDn('child6',11)"><FONT CLASS=menu>Extended DataBase</FONT></A>
C7_1;<A class="explorer" HREF="/prospect/asp/bi.asp?tn=rates_setup"onmouseover="linkUp('child7',1)"onmouseout="linkDn('child7',1)"><FONT CLASS=menu>Rating Parameters</FONT></A>
C8_1;<A class="explorer" HREF="/prospect/asp/group_admin.asp"onmouseover="linkUp('child8',1)"onmouseout="linkDn('child8',1)"><FONT CLASS=menu>Maintain Groups</FONT></A>
C8_2;<A class="explorer" HREF="/prospect/asp/user_admin.asp"onmouseover="linkUp('child8',2)"onmouseout="linkDn('child8',2)"><FONT CLASS=menu>Maintain Users</FONT></A>
